// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.6.1
// source: proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Timestamp } from 'google/protobuf/timestamp';
import { Empty } from 'google/protobuf/empty';
import { Observable } from 'rxjs';

export const protobufPackage = 'user';

export interface GetUserBuyerWithEmailRequest {
  email: string;
}

export interface GetUserBuyerWithUsernameRequest {
  username: string;
}

export interface GetUserBuyerResponse {
  buyer?: BuyerData | undefined;
  null?: Empty | undefined;
}

export interface BuyerData {
  id: string;
  username: string;
  email: string;
  profilePublicId: string;
  country: string;
  isSeller: boolean;
  purchasedGigs: string[];
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}

export const USER_PACKAGE_NAME = 'user';

export interface UserServiceClient {
  getUserBuyerWithEmail(
    request: GetUserBuyerWithEmailRequest,
  ): Observable<GetUserBuyerResponse>;

  getUserBuyerWithUsername(
    request: GetUserBuyerWithUsernameRequest,
  ): Observable<GetUserBuyerResponse>;
}

export interface UserServiceController {
  getUserBuyerWithEmail(
    request: GetUserBuyerWithEmailRequest,
  ):
    | Promise<GetUserBuyerResponse>
    | Observable<GetUserBuyerResponse>
    | GetUserBuyerResponse;

  getUserBuyerWithUsername(
    request: GetUserBuyerWithUsernameRequest,
  ):
    | Promise<GetUserBuyerResponse>
    | Observable<GetUserBuyerResponse>
    | GetUserBuyerResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getUserBuyerWithEmail',
      'getUserBuyerWithUsername',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('UserService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('UserService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const USER_SERVICE_NAME = 'UserService';
