// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.6.1
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "auth";

export interface CreateAuthDto {
  /** The username of the user. */
  username: string;
  /** The password of the user. */
  password: string;
  /** The country of the user. */
  country: string;
  /** The email of the user. */
  email: string;
  /** The optional profile picture of the user. */
  profilePicture: string;
  /** The optional name of the browser used by the user. */
  browserName: string;
  /** The optional type of device used by the user. */
  deviceType: string;
}

export interface Auth {
  /** The unique identifier for the user. */
  id: number;
  /** The username of the user. */
  username: string;
  /** The password of the user. */
  password: string;
  /** The public profile ID of the user, which is optional. */
  profilePublicId: string;
  /** The email of the user. */
  email: string;
  /** The country of the user. */
  country: string;
  /** The email verification token for the user, which is optional. */
  emailVerificationToken: string;
  /** Indicates whether the user's email is verified. */
  emailVerified: boolean;
  /** The name of the browser used by the user. */
  browserName: string;
  /** The type of device used by the user. */
  deviceType: string;
  /** The one-time password (OTP) for the user, which is optional. */
  otp: string;
  /** The expiration date and time for the OTP, which is optional. */
  otpExpiration:
    | Timestamp
    | undefined;
  /** The date and time when the user was created. */
  createdAt:
    | Timestamp
    | undefined;
  /** The token for resetting the user's password, which is optional. */
  passwordResetToken: string;
  /** The expiration date and time for the password reset token, which is optional. */
  passwordResetExpires: Timestamp | undefined;
}

export interface LoginAuthRequest {
  /** The email of the user. */
  email: string;
  /** The password of the user. */
  password: string;
  /** The optional name of the browser used by the user. */
  browserName: string;
  /** The optional type of device used by the user. */
  deviceType: string;
}

export interface LoginAuthResponse {
  accessToken: string;
  refreshToken: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  createUser(request: CreateAuthDto): Observable<Auth>;

  getUserByCredential(request: LoginAuthRequest): Observable<Auth>;
}

export interface AuthServiceController {
  createUser(request: CreateAuthDto): Promise<Auth> | Observable<Auth> | Auth;

  getUserByCredential(request: LoginAuthRequest): Promise<Auth> | Observable<Auth> | Auth;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "getUserByCredential"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
